name: Continuous Integration
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  strategy:
    matrix:
      node_version: [10, 12, 14]
      os: [ubuntu-latest]
  runs-on: ${{ matrix.os }}
  install:
    name: Install dependencies
    if: ${{ !(startsWith(github.event.pull_request.title, 'chore') || startsWith(github.event.pull_request.title, 'ci')) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: yarn install
  lint:
    name: Lint Checks
    needs: install
    if: ${{ !startsWith(github.event.pull_request.title, 'docs') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Restore Node.js modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Lint pull request title
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint
      - name: Lint commits count
        if: ${{ github.event.pull_request.commits > 3 }}
        run: echo "::error::The commits of pull request should not be more than 3 && exit 1"
  build:
    name: Build Package
    needs: lint
    if: ${{ !startsWith(github.event.pull_request.title, 'docs') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Restore Node.js modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Build package
        run: yarn build
